[package]
edition = "2021"
name = "wgshadertoy"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
binrw = "0.10"
bytemuck = {version = "1.12", features = ["derive"]}
egui = "0.19"
egui-winit = "0.19"
egui_wgpu_backend = "0.19"
env_logger = "0.9"
futures = "0.3"
image = "0.24"
log = "0.4"
naga = { version = "0.10", features = ["wgsl-in"] }
rfd = "0.10"
wgpu = "0.13"
winit = "0.27"
